### ISSUE TITLE
Call to set SPS-PicturePlaceholderState is failing 

### ISSUE THREAD

**Issue by LoungeFlyZ** [Hyperfish/PhotoImporterExporter#1]
The call to set SPS-PicturePlaceholderState property in a users profile after uploading their photo(s) fails with an access denied error even when using a Global Admin account.

Investigating.

**Comment by J04nn4** [comment]
Hi, any updates on this error? thanks

**Comment by fela98** [comment]
Hi, I'm getting the exact same issue. Any update on this? This tool would be really useful for us if we can use it for importing the profile pictures to SharePoint.

**Comment by LoungeFlyZ** [comment]
Thanks for the PR @fela98 ... i obviously borked up a change and used the wrong clientcontext for setting the profile properties.  Thanks for catching it!
